(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-run-classic-mode-vm nil)
 '(jde-bug-debugger-host-address "scallion.cs.umass.edu")
 '(jde-db-option-application-args (quote ("start")))
 '(jde-db-classic-mode-vm t)
 '(jde-ant-home "h:\\Apache\\tomcat\\jakarta-ant")
 '(jde-bug-vm-executable (quote ("java")))
 '(jde-build-function (quote (jde-ant-build)))
 '(jde-debugger (quote ("JDEbug")))
 '(jde-db-option-connect-address "javahome")
 '(jde-vm-path "H:\\jdk1.1.8\\bin\\java")
 '(jde-ant-program "H:\\apache\\tomcat\\jakarta-ant\\bin\\ant")
 '(jde-sourcepath (quote ("l:\\extalg\\extalgjava")))
 '(jde-ant-buildfile "l:/extalg/extalgjava/build.xml")
 '(jde-bug-jre-home "H:\\jdk1.1.8"))
